[package]
name = "hyprscratch"
version = "0.2.7"
edition = "2021"
license = "MIT"
description = "Scratchpad functionality for Hyprland"
homepage = "https://github.com/sasheto-phizika/hyprscratch"
repository = "https://github.com/sasheto-phizika/hyprscratch"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = "0.3.13"
regex = "1.10.3"
